const menu = [
  {
    id: 1,
    title: 'butter pancakes',
    category: 'breakfast',
    price: 4.20,
    img: './images/item-1.jpeg',
    desc: `BevEats Testing Product `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 4.20,
    img: './images/item-2.jpeg',
    desc: `BevEats Testing Product`,
  },
  {
    id: 3,
    title: 'Cream milkshake',
    category: 'shakes',
    price: 4.20,
    img: './images/item-3.jpeg',
    desc: `BevEats Testing Product`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 4.20,
    img: './images/item-4.jpeg',
    desc: `BevEats Testing Product`,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 4.20,
    img: './images/item-5.jpeg',
    desc: `BevEats Testing Product`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 4.20,
    img: './images/item-6.jpeg',
    desc: `BevEats Testing Product`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 4.20,
    img: './images/item-7.jpeg',
    desc: `BevEats Testing Product`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 4.20,
    img: './images/item-8.jpeg',
    desc: `BevEats Testing Product`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 4.20,
    img: './images/item-9.jpeg',
    desc: `BevEats Testing Product`,
  },
];
export default menu;
